version: '3.9'
services:
  backend:
    build: .
    ports:
      # localport : dockerport
      - "8000:8000"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes: 
      - .:/app
    depends_on:    # the db container runs first then backend container, we need the db to run before the backend
      - db
      - redis    

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root    
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      # have to use a different localport because I have mysql installed
      - "33066:3306"     # linux connect: mysql -P 33066 --protocol=tcp -u root -p

  redis: 
    image: redis
    ports: 
      - 6379:6379

  # mailhog to intercept emails with nondemailer
  mailhog:
    image: "mailhog/mailhog"
    container_name: "mailhog"
    ports:
      - 8025:8025
      - 1025:1025